/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_prod_home (void)
{
  GtkWidget *window_prod_home;
  GtkWidget *notebook1;
  GtkWidget *eventbox13;
  GtkWidget *fixed1;
  GtkWidget *eventbox1;
  GtkWidget *scrolledwindow_home;
  GtkWidget *viewport1;
  GtkWidget *fixed2;
  GtkWidget *treeview1_home_list;
  GtkWidget *fixed3;
  GtkWidget *entry1_add_prod;
  GtkWidget *label8;
  GtkWidget *entry3_add_prod;
  GtkObject *spinbutton2_add_prod_adj;
  GtkWidget *spinbutton2_add_prod;
  GtkObject *spinbutton3_add_prod_adj;
  GtkWidget *spinbutton3_add_prod;
  GtkObject *spinbutton4_add_prod_adj;
  GtkWidget *spinbutton4_add_prod;
  GtkObject *spinbutton9_add_prod_adj;
  GtkWidget *spinbutton9_add_prod;
  GtkWidget *eventbox4;
  GtkWidget *button4_ref_home;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label53;
  GtkWidget *eventbox5;
  GtkWidget *button5_search_prod;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label19;
  GtkWidget *eventbox8;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport3;
  GtkWidget *fixed5;
  GtkWidget *treeview3_show_out;
  GtkWidget *eventbox9;
  GtkWidget *button3_disp_out_prod;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label15;
  GtkWidget *entry2_add_prod;
  GtkWidget *eventbox11;
  GtkWidget *label6_notice;
  GtkWidget *eventbox17;
  GtkWidget *label14;
  GtkWidget *eventbox18;
  GtkWidget *combo1_add_prod;
  GList *combo1_add_prod_items = NULL;
  GtkWidget *entry4_add_prod;
  GtkWidget *eventbox19;
  GtkWidget *label13;
  GtkWidget *eventbox20;
  GtkWidget *label12;
  GtkWidget *eventbox21;
  GtkWidget *label9;
  GtkWidget *eventbox22;
  GtkWidget *label7;
  GtkWidget *eventbox42;
  GtkWidget *button2_add_prod;
  GtkWidget *alignment13;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label58;
  GtkWidget *eventbox43;
  GtkWidget *label10;
  GtkWidget *eventbox44;
  GtkWidget *label11;
  GtkWidget *eventbox45;
  GtkWidget *label17;
  GtkWidget *eventbox46;
  GtkWidget *label16;
  GtkWidget *image15;
  GtkWidget *label1;
  GtkWidget *eventbox39;
  GtkWidget *alignment12;
  GtkWidget *eventbox50;
  GtkWidget *fixed12;
  GtkWidget *fixed13;
  GtkWidget *repl2;
  GtkWidget *repl3;
  GtkWidget *fixed14;
  GtkWidget *repl1;
  GtkWidget *eventbox52;
  GtkWidget *verif_id_prod;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label50;
  GtkWidget *eventbox53;
  GtkWidget *label49;
  GtkObject *spinbutton5_mod_prod_adj;
  GtkWidget *spinbutton5_mod_prod;
  GtkObject *spinbutton6_mod_prod_adj;
  GtkWidget *spinbutton6_mod_prod;
  GtkObject *spinbutton7_mod_prod_adj;
  GtkWidget *spinbutton7_mod_prod;
  GtkObject *spinbutton8_mod_prod_adj;
  GtkWidget *spinbutton8_mod_prod;
  GtkWidget *entry24_mod_prod;
  GtkWidget *eventbox25;
  GtkWidget *label44;
  GtkWidget *eventbox30;
  GtkWidget *label47;
  GtkWidget *eventbox32;
  GtkWidget *stockA;
  GSList *stockA_group = NULL;
  GtkWidget *eventbox33;
  GtkWidget *label52;
  GtkWidget *eventbox34;
  GtkWidget *button9_mod_prod;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label51;
  GtkWidget *eventbox35;
  GtkWidget *stockB;
  GtkWidget *label55;
  GtkWidget *label45;
  GtkWidget *eventbox51;
  GtkWidget *label46;
  GtkWidget *eventbox38;
  GtkWidget *label56;
  GtkWidget *eventbox41;
  GtkWidget *label57;
  GtkWidget *image14;
  GtkWidget *label2;

  window_prod_home = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_prod_home), _("Stock Managment"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window_prod_home), notebook1);
  gtk_widget_set_size_request (notebook1, 1280, 563);

  eventbox13 = gtk_event_box_new ();
  gtk_widget_show (eventbox13);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox13);
  gtk_notebook_set_tab_label_packing (GTK_NOTEBOOK (notebook1), eventbox13,
                                      FALSE, FALSE, GTK_PACK_START);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (eventbox13), fixed1);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_fixed_put (GTK_FIXED (fixed1), eventbox1, 0, 0);
  gtk_widget_set_size_request (eventbox1, 584, 312);

  scrolledwindow_home = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_home);
  gtk_container_add (GTK_CONTAINER (eventbox1), scrolledwindow_home);
  gtk_widget_set_size_request (scrolledwindow_home, 584, 312);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_home), viewport1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed2);

  treeview1_home_list = gtk_tree_view_new ();
  gtk_widget_show (treeview1_home_list);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1_home_list, 0, 0);
  gtk_widget_set_size_request (treeview1_home_list, 568, 296);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed1), fixed3, 24, 8);
  gtk_widget_set_size_request (fixed3, 0, 0);

  entry1_add_prod = gtk_entry_new ();
  gtk_widget_show (entry1_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1_add_prod, 112, 360);
  gtk_widget_set_size_request (entry1_add_prod, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_add_prod), 8226);

  label8 = gtk_label_new ("");
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 24, 368);
  gtk_widget_set_size_request (label8, 49, 17);

  entry3_add_prod = gtk_entry_new ();
  gtk_widget_show (entry3_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3_add_prod, 400, 400);
  gtk_widget_set_size_request (entry3_add_prod, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_add_prod), 8226);

  spinbutton2_add_prod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton2_add_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_add_prod_adj), 1, 0);
  gtk_widget_show (spinbutton2_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton2_add_prod, 112, 496);
  gtk_widget_set_size_request (spinbutton2_add_prod, 60, 27);

  spinbutton3_add_prod_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton3_add_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_add_prod_adj), 1, 0);
  gtk_widget_show (spinbutton3_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton3_add_prod, 248, 496);
  gtk_widget_set_size_request (spinbutton3_add_prod, 60, 27);

  spinbutton4_add_prod_adj = gtk_adjustment_new (2000, 2000, 3000, 1, 10, 10);
  spinbutton4_add_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_add_prod_adj), 1, 0);
  gtk_widget_show (spinbutton4_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton4_add_prod, 400, 496);
  gtk_widget_set_size_request (spinbutton4_add_prod, 60, 27);

  spinbutton9_add_prod_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton9_add_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_add_prod_adj), 1, 0);
  gtk_widget_show (spinbutton9_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton9_add_prod, 112, 448);
  gtk_widget_set_size_request (spinbutton9_add_prod, 56, 24);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox4, 600, 64);
  gtk_widget_set_size_request (eventbox4, 104, 29);

  button4_ref_home = gtk_button_new ();
  gtk_widget_show (button4_ref_home);
  gtk_container_add (GTK_CONTAINER (eventbox4), button4_ref_home);
  gtk_widget_set_size_request (button4_ref_home, 104, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button4_ref_home), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label53 = gtk_label_new_with_mnemonic (_("<b><span color=\"#4494fc\">Refresh</span></b>"));
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (hbox10), label53, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox5, 600, 96);
  gtk_widget_set_size_request (eventbox5, 104, 29);

  button5_search_prod = gtk_button_new ();
  gtk_widget_show (button5_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox5), button5_search_prod);
  gtk_widget_set_size_request (button5_search_prod, 104, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5_search_prod), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("<b><span color=\"#003296\">Search</span></b>"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox5), label19, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox8, 792, 48);
  gtk_widget_set_size_request (eventbox8, 456, 328);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (eventbox8), scrolledwindow3);
  gtk_widget_set_size_request (scrolledwindow3, 456, 328);

  viewport3 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport3);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport3);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (viewport3), fixed5);

  treeview3_show_out = gtk_tree_view_new ();
  gtk_widget_show (treeview3_show_out);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview3_show_out, 0, 0);
  gtk_widget_set_size_request (treeview3_show_out, 448, 320);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview3_show_out), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview3_show_out), TRUE);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox9, 1080, 384);
  gtk_widget_set_size_request (eventbox9, 136, 37);

  button3_disp_out_prod = gtk_button_new ();
  gtk_widget_show (button3_disp_out_prod);
  gtk_container_add (GTK_CONTAINER (eventbox9), button3_disp_out_prod);
  gtk_widget_set_size_request (button3_disp_out_prod, 136, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3_disp_out_prod), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("<b><span color=\"#ed5a11\">Display</span></b>"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox3), label15, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  entry2_add_prod = gtk_entry_new ();
  gtk_widget_show (entry2_add_prod);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2_add_prod, 400, 360);
  gtk_widget_set_size_request (entry2_add_prod, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_add_prod), 8226);

  eventbox11 = gtk_event_box_new ();
  gtk_widget_show (eventbox11);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox11, 0, 304);
  gtk_widget_set_size_request (eventbox11, 336, 40);

  label6_notice = gtk_label_new_with_mnemonic (_("<b><span color =\"RED\">(Press Twice if You Want to Delete a Product)</span></b>"));
  gtk_widget_show (label6_notice);
  gtk_container_add (GTK_CONTAINER (eventbox11), label6_notice);
  gtk_widget_set_size_request (label6_notice, 336, 40);
  gtk_label_set_use_markup (GTK_LABEL (label6_notice), TRUE);

  eventbox17 = gtk_event_box_new ();
  gtk_widget_show (eventbox17);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox17, 24, 496);
  gtk_widget_set_size_request (eventbox17, 64, 25);

  label14 = gtk_label_new (_("<b><span color=\"Black\">Day</span></b>"));
  gtk_widget_show (label14);
  gtk_container_add (GTK_CONTAINER (eventbox17), label14);
  gtk_widget_set_size_request (label14, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  eventbox18 = gtk_event_box_new ();
  gtk_widget_show (eventbox18);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox18, 400, 440);
  gtk_widget_set_size_request (eventbox18, 187, 27);

  combo1_add_prod = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (combo1_add_prod)->popwin),
                     "GladeParentKey", combo1_add_prod);
  gtk_widget_show (combo1_add_prod);
  gtk_container_add (GTK_CONTAINER (eventbox18), combo1_add_prod);
  gtk_widget_set_size_request (combo1_add_prod, 187, 27);
  gtk_combo_set_value_in_list (GTK_COMBO (combo1_add_prod), TRUE, FALSE);
  gtk_combo_set_use_arrows_always (GTK_COMBO (combo1_add_prod), TRUE);
  combo1_add_prod_items = g_list_append (combo1_add_prod_items, (gpointer) _("StockA"));
  combo1_add_prod_items = g_list_append (combo1_add_prod_items, (gpointer) _("StockB"));
  gtk_combo_set_popdown_strings (GTK_COMBO (combo1_add_prod), combo1_add_prod_items);
  g_list_free (combo1_add_prod_items);

  entry4_add_prod = GTK_COMBO (combo1_add_prod)->entry;
  gtk_widget_show (entry4_add_prod);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_add_prod), 8226);

  eventbox19 = gtk_event_box_new ();
  gtk_widget_show (eventbox19);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox19, 320, 496);
  gtk_widget_set_size_request (eventbox19, 64, 25);

  label13 = gtk_label_new (_("<b><span color=\"Black\">Year</span></b>"));
  gtk_widget_show (label13);
  gtk_container_add (GTK_CONTAINER (eventbox19), label13);
  gtk_widget_set_size_request (label13, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);

  eventbox20 = gtk_event_box_new ();
  gtk_widget_show (eventbox20);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox20, 176, 496);
  gtk_widget_set_size_request (eventbox20, 64, 25);

  label12 = gtk_label_new (_("<b><span color=\"Black\">Month</span></b>"));
  gtk_widget_show (label12);
  gtk_container_add (GTK_CONTAINER (eventbox20), label12);
  gtk_widget_set_size_request (label12, 64, 25);
  gtk_label_set_use_markup (GTK_LABEL (label12), TRUE);

  eventbox21 = gtk_event_box_new ();
  gtk_widget_show (eventbox21);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox21, 0, 440);
  gtk_widget_set_size_request (eventbox21, 112, 33);

  label9 = gtk_label_new (_("<b><span color=\"Black\">Quantity</span></b>"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (eventbox21), label9);
  gtk_widget_set_size_request (label9, 112, 33);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);

  eventbox22 = gtk_event_box_new ();
  gtk_widget_show (eventbox22);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox22, 0, 360);
  gtk_widget_set_size_request (eventbox22, 112, 33);

  label7 = gtk_label_new (_("<b><span color=\"Black\">Identifier</span></b>"));
  gtk_widget_show (label7);
  gtk_container_add (GTK_CONTAINER (eventbox22), label7);
  gtk_widget_set_size_request (label7, 112, 33);
  gtk_label_set_use_markup (GTK_LABEL (label7), TRUE);

  eventbox42 = gtk_event_box_new ();
  gtk_widget_show (eventbox42);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox42, 600, 32);
  gtk_widget_set_size_request (eventbox42, 104, 29);

  button2_add_prod = gtk_button_new ();
  gtk_widget_show (button2_add_prod);
  gtk_container_add (GTK_CONTAINER (eventbox42), button2_add_prod);
  gtk_widget_set_size_request (button2_add_prod, 104, 29);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button2_add_prod), alignment13);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label58 = gtk_label_new_with_mnemonic (_("<b><span color=\"#52c458\">Add</span></b>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox11), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  eventbox43 = gtk_event_box_new ();
  gtk_widget_show (eventbox43);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox43, 304, 360);
  gtk_widget_set_size_request (eventbox43, 96, 33);

  label10 = gtk_label_new_with_mnemonic (_("<b><span color=\"Black\">Name</span></b>"));
  gtk_widget_show (label10);
  gtk_container_add (GTK_CONTAINER (eventbox43), label10);
  gtk_widget_set_size_request (label10, 96, 33);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  eventbox44 = gtk_event_box_new ();
  gtk_widget_show (eventbox44);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox44, 320, 400);
  gtk_widget_set_size_request (eventbox44, 64, 33);

  label11 = gtk_label_new (_("<b><span color=\"Black\">Price</span></b>"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (eventbox44), label11);
  gtk_widget_set_size_request (label11, 64, 33);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  eventbox45 = gtk_event_box_new ();
  gtk_widget_show (eventbox45);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox45, 312, 440);
  gtk_widget_set_size_request (eventbox45, 72, 25);

  label17 = gtk_label_new (_("<b><span color=\"Black\">Location</span></b>"));
  gtk_widget_show (label17);
  gtk_container_add (GTK_CONTAINER (eventbox45), label17);
  gtk_widget_set_size_request (label17, 72, 25);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  eventbox46 = gtk_event_box_new ();
  gtk_widget_show (eventbox46);
  gtk_fixed_put (GTK_FIXED (fixed3), eventbox46, 928, 0);
  gtk_widget_set_size_request (eventbox46, 240, 41);

  label16 = gtk_label_new (_("<b><span color=\"#373e4a\">List of Products Out of Stock</span></b>"));
  gtk_widget_show (label16);
  gtk_container_add (GTK_CONTAINER (eventbox46), label16);
  gtk_widget_set_size_request (label16, 240, 41);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  image15 = create_pixmap (window_prod_home, "siala2.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed3), image15, -24, -8);
  gtk_widget_set_size_request (image15, 1296, 576);

  label1 = gtk_label_new_with_mnemonic (_("<b><span color=\"#373e4a\">Home</span></b>"));
  gtk_widget_show (label1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label1);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  eventbox39 = gtk_event_box_new ();
  gtk_widget_show (eventbox39);
  gtk_container_add (GTK_CONTAINER (notebook1), eventbox39);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (eventbox39), alignment12);

  eventbox50 = gtk_event_box_new ();
  gtk_widget_show (eventbox50);
  gtk_container_add (GTK_CONTAINER (alignment12), eventbox50);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (eventbox50), fixed12);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed12), fixed13, 64, 8);
  gtk_widget_set_size_request (fixed13, 16, 241);

  repl2 = gtk_entry_new ();
  gtk_widget_show (repl2);
  gtk_fixed_put (GTK_FIXED (fixed13), repl2, 144, 232);
  gtk_widget_set_size_request (repl2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (repl2), 8226);

  repl3 = gtk_entry_new ();
  gtk_widget_show (repl3);
  gtk_fixed_put (GTK_FIXED (fixed13), repl3, 144, 272);
  gtk_widget_set_size_request (repl3, 72, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (repl3), 8226);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_fixed_put (GTK_FIXED (fixed13), fixed14, 0, 0);
  gtk_widget_set_size_request (fixed14, 0, 0);

  repl1 = gtk_entry_new ();
  gtk_widget_show (repl1);
  gtk_fixed_put (GTK_FIXED (fixed14), repl1, 137, 152);
  gtk_widget_set_size_request (repl1, 192, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (repl1), 8226);

  eventbox52 = gtk_event_box_new ();
  gtk_widget_show (eventbox52);
  gtk_fixed_put (GTK_FIXED (fixed14), eventbox52, 336, 149);
  gtk_widget_set_size_request (eventbox52, 112, 37);

  verif_id_prod = gtk_button_new ();
  gtk_widget_show (verif_id_prod);
  gtk_container_add (GTK_CONTAINER (eventbox52), verif_id_prod);
  gtk_widget_set_size_request (verif_id_prod, 112, 37);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (verif_id_prod), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("<b><span color=\"#373e4a\">Check</span><span color=\"#ed5a11\"> ID</span></b>"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox8), label50, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  eventbox53 = gtk_event_box_new ();
  gtk_widget_show (eventbox53);
  gtk_fixed_put (GTK_FIXED (fixed14), eventbox53, 8, 148);
  gtk_widget_set_size_request (eventbox53, 120, 41);

  label49 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Identifier</span></b>"));
  gtk_widget_show (label49);
  gtk_container_add (GTK_CONTAINER (eventbox53), label49);
  gtk_widget_set_size_request (label49, 120, 41);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  spinbutton5_mod_prod_adj = gtk_adjustment_new (1, 0, 2000, 1, 10, 10);
  spinbutton5_mod_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_mod_prod_adj), 1, 0);
  gtk_widget_show (spinbutton5_mod_prod);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton5_mod_prod, 144, 304);
  gtk_widget_set_size_request (spinbutton5_mod_prod, 56, 27);

  spinbutton6_mod_prod_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton6_mod_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_mod_prod_adj), 1, 0);
  gtk_widget_show (spinbutton6_mod_prod);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton6_mod_prod, 144, 344);
  gtk_widget_set_size_request (spinbutton6_mod_prod, 48, 27);

  spinbutton7_mod_prod_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton7_mod_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_mod_prod_adj), 1, 0);
  gtk_widget_show (spinbutton7_mod_prod);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton7_mod_prod, 208, 344);
  gtk_widget_set_size_request (spinbutton7_mod_prod, 60, 27);

  spinbutton8_mod_prod_adj = gtk_adjustment_new (2000, 2000, 3000, 1, 10, 10);
  spinbutton8_mod_prod = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_mod_prod_adj), 1, 0);
  gtk_widget_show (spinbutton8_mod_prod);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton8_mod_prod, 272, 344);
  gtk_widget_set_size_request (spinbutton8_mod_prod, 60, 27);

  entry24_mod_prod = gtk_entry_new ();
  gtk_widget_show (entry24_mod_prod);
  gtk_fixed_put (GTK_FIXED (fixed13), entry24_mod_prod, 144, 416);
  gtk_widget_set_size_request (entry24_mod_prod, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24_mod_prod), 8226);

  eventbox25 = gtk_event_box_new ();
  gtk_widget_show (eventbox25);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox25, 56, 264);
  gtk_widget_set_size_request (eventbox25, 65, 25);

  label44 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Price</span></b>"));
  gtk_widget_show (label44);
  gtk_container_add (GTK_CONTAINER (eventbox25), label44);
  gtk_widget_set_size_request (label44, 65, 25);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  eventbox30 = gtk_event_box_new ();
  gtk_widget_show (eventbox30);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox30, 32, 384);
  gtk_widget_set_size_request (eventbox30, 120, 25);

  label47 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Stock Location</span></b>"));
  gtk_widget_show (label47);
  gtk_container_add (GTK_CONTAINER (eventbox30), label47);
  gtk_widget_set_size_request (label47, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  eventbox32 = gtk_event_box_new ();
  gtk_widget_show (eventbox32);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox32, 160, 384);
  gtk_widget_set_size_request (eventbox32, 116, 24);

  stockA = gtk_radio_button_new_with_mnemonic (NULL, _("StockA"));
  gtk_widget_show (stockA);
  gtk_container_add (GTK_CONTAINER (eventbox32), stockA);
  gtk_widget_set_size_request (stockA, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (stockA), stockA_group);
  stockA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (stockA));

  eventbox33 = gtk_event_box_new ();
  gtk_widget_show (eventbox33);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox33, 80, 424);
  gtk_widget_set_size_request (eventbox33, 49, 17);

  label52 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">ID</span></b>"));
  gtk_widget_show (label52);
  gtk_container_add (GTK_CONTAINER (eventbox33), label52);
  gtk_widget_set_size_request (label52, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  eventbox34 = gtk_event_box_new ();
  gtk_widget_show (eventbox34);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox34, 144, 464);
  gtk_widget_set_size_request (eventbox34, 184, 40);

  button9_mod_prod = gtk_button_new ();
  gtk_widget_show (button9_mod_prod);
  gtk_container_add (GTK_CONTAINER (eventbox34), button9_mod_prod);
  gtk_widget_set_size_request (button9_mod_prod, 184, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button9_mod_prod), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label51 = gtk_label_new_with_mnemonic (_("<b><span color=\"#373e4a\">Update</span></b>"));
  gtk_widget_show (label51);
  gtk_box_pack_start (GTK_BOX (hbox9), label51, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  eventbox35 = gtk_event_box_new ();
  gtk_widget_show (eventbox35);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox35, 280, 384);
  gtk_widget_set_size_request (eventbox35, 116, 24);

  stockB = gtk_radio_button_new_with_mnemonic (NULL, _("StockB"));
  gtk_widget_show (stockB);
  gtk_container_add (GTK_CONTAINER (eventbox35), stockB);
  gtk_widget_set_size_request (stockB, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (stockB), stockA_group);
  stockA_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (stockB));

  label55 = gtk_label_new (_("label55"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed13), label55, 64, 232);
  gtk_widget_set_size_request (label55, 49, 17);

  label45 = gtk_label_new (_("Quantity"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed13), label45, 64, 304);
  gtk_widget_set_size_request (label45, 80, 32);

  eventbox51 = gtk_event_box_new ();
  gtk_widget_show (eventbox51);
  gtk_fixed_put (GTK_FIXED (fixed13), eventbox51, 16, 344);
  gtk_widget_set_size_request (eventbox51, 120, 25);

  label46 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Date of Purchase</span></b>"));
  gtk_widget_show (label46);
  gtk_container_add (GTK_CONTAINER (eventbox51), label46);
  gtk_widget_set_size_request (label46, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  eventbox38 = gtk_event_box_new ();
  gtk_widget_show (eventbox38);
  gtk_fixed_put (GTK_FIXED (fixed12), eventbox38, 104, 232);
  gtk_widget_set_size_request (eventbox38, 88, 33);

  label56 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Name</span></b>"));
  gtk_widget_show (label56);
  gtk_container_add (GTK_CONTAINER (eventbox38), label56);
  gtk_widget_set_size_request (label56, 88, 33);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  eventbox41 = gtk_event_box_new ();
  gtk_widget_show (eventbox41);
  gtk_fixed_put (GTK_FIXED (fixed12), eventbox41, 112, 312);
  gtk_widget_set_size_request (eventbox41, 88, 33);

  label57 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Quantity</span></b>"));
  gtk_widget_show (label57);
  gtk_container_add (GTK_CONTAINER (eventbox41), label57);
  gtk_widget_set_size_request (label57, 88, 33);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  image14 = create_pixmap (window_prod_home, "siala2.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed12), image14, 0, 0);
  gtk_widget_set_size_request (image14, 1296, 576);

  label2 = gtk_label_new_with_mnemonic (_("<b><span color=\"#0570fc\">Modify</span></b>"));
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  g_signal_connect ((gpointer) treeview1_home_list, "row_activated",
                    G_CALLBACK (on_treeview1_home_list_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button4_ref_home, "clicked",
                    G_CALLBACK (on_button4_ref_home_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_search_prod, "clicked",
                    G_CALLBACK (on_button5_search_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_disp_out_prod, "clicked",
                    G_CALLBACK (on_button3_disp_out_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_add_prod, "clicked",
                    G_CALLBACK (on_button2_add_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) verif_id_prod, "clicked",
                    G_CALLBACK (on_verif_id_prod_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9_mod_prod, "clicked",
                    G_CALLBACK (on_button9_mod_prod_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label10), entry2_add_prod);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label49), repl1);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label46), spinbutton6_mod_prod);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_prod_home, window_prod_home, "window_prod_home");
  GLADE_HOOKUP_OBJECT (window_prod_home, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox13, "eventbox13");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (window_prod_home, scrolledwindow_home, "scrolledwindow_home");
  GLADE_HOOKUP_OBJECT (window_prod_home, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window_prod_home, treeview1_home_list, "treeview1_home_list");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_prod_home, entry1_add_prod, "entry1_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, label8, "label8");
  GLADE_HOOKUP_OBJECT (window_prod_home, entry3_add_prod, "entry3_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton2_add_prod, "spinbutton2_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton3_add_prod, "spinbutton3_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton4_add_prod, "spinbutton4_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton9_add_prod, "spinbutton9_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (window_prod_home, button4_ref_home, "button4_ref_home");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_prod_home, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_prod_home, label53, "label53");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (window_prod_home, button5_search_prod, "button5_search_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_prod_home, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_prod_home, label19, "label19");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (window_prod_home, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (window_prod_home, viewport3, "viewport3");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window_prod_home, treeview3_show_out, "treeview3_show_out");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (window_prod_home, button3_disp_out_prod, "button3_disp_out_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window_prod_home, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_prod_home, label15, "label15");
  GLADE_HOOKUP_OBJECT (window_prod_home, entry2_add_prod, "entry2_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox11, "eventbox11");
  GLADE_HOOKUP_OBJECT (window_prod_home, label6_notice, "label6_notice");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox17, "eventbox17");
  GLADE_HOOKUP_OBJECT (window_prod_home, label14, "label14");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox18, "eventbox18");
  GLADE_HOOKUP_OBJECT (window_prod_home, combo1_add_prod, "combo1_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, entry4_add_prod, "entry4_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox19, "eventbox19");
  GLADE_HOOKUP_OBJECT (window_prod_home, label13, "label13");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox20, "eventbox20");
  GLADE_HOOKUP_OBJECT (window_prod_home, label12, "label12");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox21, "eventbox21");
  GLADE_HOOKUP_OBJECT (window_prod_home, label9, "label9");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox22, "eventbox22");
  GLADE_HOOKUP_OBJECT (window_prod_home, label7, "label7");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox42, "eventbox42");
  GLADE_HOOKUP_OBJECT (window_prod_home, button2_add_prod, "button2_add_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window_prod_home, image13, "image13");
  GLADE_HOOKUP_OBJECT (window_prod_home, label58, "label58");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox43, "eventbox43");
  GLADE_HOOKUP_OBJECT (window_prod_home, label10, "label10");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox44, "eventbox44");
  GLADE_HOOKUP_OBJECT (window_prod_home, label11, "label11");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox45, "eventbox45");
  GLADE_HOOKUP_OBJECT (window_prod_home, label17, "label17");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox46, "eventbox46");
  GLADE_HOOKUP_OBJECT (window_prod_home, label16, "label16");
  GLADE_HOOKUP_OBJECT (window_prod_home, image15, "image15");
  GLADE_HOOKUP_OBJECT (window_prod_home, label1, "label1");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox39, "eventbox39");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox50, "eventbox50");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (window_prod_home, repl2, "repl2");
  GLADE_HOOKUP_OBJECT (window_prod_home, repl3, "repl3");
  GLADE_HOOKUP_OBJECT (window_prod_home, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window_prod_home, repl1, "repl1");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox52, "eventbox52");
  GLADE_HOOKUP_OBJECT (window_prod_home, verif_id_prod, "verif_id_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_prod_home, image8, "image8");
  GLADE_HOOKUP_OBJECT (window_prod_home, label50, "label50");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox53, "eventbox53");
  GLADE_HOOKUP_OBJECT (window_prod_home, label49, "label49");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton5_mod_prod, "spinbutton5_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton6_mod_prod, "spinbutton6_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton7_mod_prod, "spinbutton7_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, spinbutton8_mod_prod, "spinbutton8_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, entry24_mod_prod, "entry24_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox25, "eventbox25");
  GLADE_HOOKUP_OBJECT (window_prod_home, label44, "label44");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox30, "eventbox30");
  GLADE_HOOKUP_OBJECT (window_prod_home, label47, "label47");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox32, "eventbox32");
  GLADE_HOOKUP_OBJECT (window_prod_home, stockA, "stockA");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox33, "eventbox33");
  GLADE_HOOKUP_OBJECT (window_prod_home, label52, "label52");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox34, "eventbox34");
  GLADE_HOOKUP_OBJECT (window_prod_home, button9_mod_prod, "button9_mod_prod");
  GLADE_HOOKUP_OBJECT (window_prod_home, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_prod_home, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_prod_home, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_prod_home, label51, "label51");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox35, "eventbox35");
  GLADE_HOOKUP_OBJECT (window_prod_home, stockB, "stockB");
  GLADE_HOOKUP_OBJECT (window_prod_home, label55, "label55");
  GLADE_HOOKUP_OBJECT (window_prod_home, label45, "label45");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox51, "eventbox51");
  GLADE_HOOKUP_OBJECT (window_prod_home, label46, "label46");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox38, "eventbox38");
  GLADE_HOOKUP_OBJECT (window_prod_home, label56, "label56");
  GLADE_HOOKUP_OBJECT (window_prod_home, eventbox41, "eventbox41");
  GLADE_HOOKUP_OBJECT (window_prod_home, label57, "label57");
  GLADE_HOOKUP_OBJECT (window_prod_home, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_prod_home, label2, "label2");

  return window_prod_home;
}

GtkWidget*
create_window_search_prod (void)
{
  GtkWidget *window_search_prod;
  GtkWidget *fixed6;
  GtkWidget *fixed7;
  GtkWidget *entry5_search_prod;
  GtkWidget *eventbox57;
  GtkWidget *label20;
  GtkWidget *eventbox58;
  GtkWidget *button6_search_prod;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label21;
  GtkWidget *eventbox54;
  GtkWidget *label5_search_prod;
  GtkWidget *eventbox55;
  GtkWidget *label22;
  GtkWidget *eventbox56;
  GtkWidget *label23;
  GtkWidget *eventbox59;
  GtkWidget *label6_search_prod;
  GtkWidget *eventbox60;
  GtkWidget *label7_search_prod;
  GtkWidget *eventbox61;
  GtkWidget *label24;
  GtkWidget *eventbox62;
  GtkWidget *label25;
  GtkWidget *eventbox63;
  GtkWidget *label8_search_prod;
  GtkWidget *eventbox64;
  GtkWidget *checkbutton1_stockA;
  GtkWidget *eventbox65;
  GtkWidget *checkbutton2_stockB;
  GtkWidget *eventbox66;
  GtkWidget *label26;
  GtkWidget *image16;

  window_search_prod = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_search_prod), _("Search Product"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (window_search_prod), fixed6);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_fixed_put (GTK_FIXED (fixed6), fixed7, 0, 0);
  gtk_widget_set_size_request (fixed7, 0, 0);

  entry5_search_prod = gtk_entry_new ();
  gtk_widget_show (entry5_search_prod);
  gtk_fixed_put (GTK_FIXED (fixed7), entry5_search_prod, 136, 80);
  gtk_widget_set_size_request (entry5_search_prod, 192, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_search_prod), 8226);

  eventbox57 = gtk_event_box_new ();
  gtk_widget_show (eventbox57);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox57, 8, 80);
  gtk_widget_set_size_request (eventbox57, 120, 41);

  label20 = gtk_label_new (_("Identifier"));
  gtk_widget_show (label20);
  gtk_container_add (GTK_CONTAINER (eventbox57), label20);
  gtk_widget_set_size_request (label20, 120, 41);

  eventbox58 = gtk_event_box_new ();
  gtk_widget_show (eventbox58);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox58, 176, 128);
  gtk_widget_set_size_request (eventbox58, 112, 37);

  button6_search_prod = gtk_button_new ();
  gtk_widget_show (button6_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox58), button6_search_prod);
  gtk_widget_set_size_request (button6_search_prod, 112, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6_search_prod), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("<b><span color=\"#52c458\">Confirm</span></b>"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox6), label21, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  eventbox54 = gtk_event_box_new ();
  gtk_widget_show (eventbox54);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox54, 152, 224);
  gtk_widget_set_size_request (eventbox54, 152, 32);

  label5_search_prod = gtk_label_new ("");
  gtk_widget_show (label5_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox54), label5_search_prod);
  gtk_widget_set_size_request (label5_search_prod, 152, 32);

  eventbox55 = gtk_event_box_new ();
  gtk_widget_show (eventbox55);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox55, 40, 232);
  gtk_widget_set_size_request (eventbox55, 96, 25);

  label22 = gtk_label_new (_("Name :"));
  gtk_widget_show (label22);
  gtk_container_add (GTK_CONTAINER (eventbox55), label22);
  gtk_widget_set_size_request (label22, 96, 25);

  eventbox56 = gtk_event_box_new ();
  gtk_widget_show (eventbox56);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox56, 56, 264);
  gtk_widget_set_size_request (eventbox56, 72, 32);

  label23 = gtk_label_new (_("price :"));
  gtk_widget_show (label23);
  gtk_container_add (GTK_CONTAINER (eventbox56), label23);
  gtk_widget_set_size_request (label23, 72, 32);

  eventbox59 = gtk_event_box_new ();
  gtk_widget_show (eventbox59);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox59, 136, 264);
  gtk_widget_set_size_request (eventbox59, 160, 33);

  label6_search_prod = gtk_label_new ("");
  gtk_widget_show (label6_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox59), label6_search_prod);
  gtk_widget_set_size_request (label6_search_prod, 160, 33);

  eventbox60 = gtk_event_box_new ();
  gtk_widget_show (eventbox60);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox60, 136, 304);
  gtk_widget_set_size_request (eventbox60, 152, 33);

  label7_search_prod = gtk_label_new ("");
  gtk_widget_show (label7_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox60), label7_search_prod);
  gtk_widget_set_size_request (label7_search_prod, 152, 33);

  eventbox61 = gtk_event_box_new ();
  gtk_widget_show (eventbox61);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox61, 40, 304);
  gtk_widget_set_size_request (eventbox61, 80, 32);

  label24 = gtk_label_new (_("Quantity :"));
  gtk_widget_show (label24);
  gtk_container_add (GTK_CONTAINER (eventbox61), label24);
  gtk_widget_set_size_request (label24, 80, 32);

  eventbox62 = gtk_event_box_new ();
  gtk_widget_show (eventbox62);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox62, 0, 344);
  gtk_widget_set_size_request (eventbox62, 120, 25);

  label25 = gtk_label_new (_("Date of Purchase :"));
  gtk_widget_show (label25);
  gtk_container_add (GTK_CONTAINER (eventbox62), label25);
  gtk_widget_set_size_request (label25, 120, 25);

  eventbox63 = gtk_event_box_new ();
  gtk_widget_show (eventbox63);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox63, 136, 344);
  gtk_widget_set_size_request (eventbox63, 144, 32);

  label8_search_prod = gtk_label_new ("");
  gtk_widget_show (label8_search_prod);
  gtk_container_add (GTK_CONTAINER (eventbox63), label8_search_prod);
  gtk_widget_set_size_request (label8_search_prod, 144, 32);

  eventbox64 = gtk_event_box_new ();
  gtk_widget_show (eventbox64);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox64, 136, 384);
  gtk_widget_set_size_request (eventbox64, 112, 25);

  checkbutton1_stockA = gtk_check_button_new_with_mnemonic (_("StockA"));
  gtk_widget_show (checkbutton1_stockA);
  gtk_container_add (GTK_CONTAINER (eventbox64), checkbutton1_stockA);
  gtk_widget_set_size_request (checkbutton1_stockA, 112, 25);

  eventbox65 = gtk_event_box_new ();
  gtk_widget_show (eventbox65);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox65, 248, 384);
  gtk_widget_set_size_request (eventbox65, 120, 24);

  checkbutton2_stockB = gtk_check_button_new_with_mnemonic (_("StockB"));
  gtk_widget_show (checkbutton2_stockB);
  gtk_container_add (GTK_CONTAINER (eventbox65), checkbutton2_stockB);
  gtk_widget_set_size_request (checkbutton2_stockB, 120, 24);

  eventbox66 = gtk_event_box_new ();
  gtk_widget_show (eventbox66);
  gtk_fixed_put (GTK_FIXED (fixed6), eventbox66, 8, 384);
  gtk_widget_set_size_request (eventbox66, 128, 25);

  label26 = gtk_label_new (_("Stock Place :"));
  gtk_widget_show (label26);
  gtk_container_add (GTK_CONTAINER (eventbox66), label26);
  gtk_widget_set_size_request (label26, 128, 25);

  image16 = create_pixmap (window_search_prod, "561776-200.png");
  gtk_widget_show (image16);
  gtk_fixed_put (GTK_FIXED (fixed6), image16, 0, 16);
  gtk_widget_set_size_request (image16, 376, 392);

  g_signal_connect ((gpointer) button6_search_prod, "clicked",
                    G_CALLBACK (on_button6_search_prod_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_search_prod, window_search_prod, "window_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window_search_prod, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_search_prod, entry5_search_prod, "entry5_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox57, "eventbox57");
  GLADE_HOOKUP_OBJECT (window_search_prod, label20, "label20");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox58, "eventbox58");
  GLADE_HOOKUP_OBJECT (window_search_prod, button6_search_prod, "button6_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_search_prod, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_search_prod, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_search_prod, label21, "label21");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox54, "eventbox54");
  GLADE_HOOKUP_OBJECT (window_search_prod, label5_search_prod, "label5_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox55, "eventbox55");
  GLADE_HOOKUP_OBJECT (window_search_prod, label22, "label22");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox56, "eventbox56");
  GLADE_HOOKUP_OBJECT (window_search_prod, label23, "label23");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox59, "eventbox59");
  GLADE_HOOKUP_OBJECT (window_search_prod, label6_search_prod, "label6_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox60, "eventbox60");
  GLADE_HOOKUP_OBJECT (window_search_prod, label7_search_prod, "label7_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox61, "eventbox61");
  GLADE_HOOKUP_OBJECT (window_search_prod, label24, "label24");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox62, "eventbox62");
  GLADE_HOOKUP_OBJECT (window_search_prod, label25, "label25");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox63, "eventbox63");
  GLADE_HOOKUP_OBJECT (window_search_prod, label8_search_prod, "label8_search_prod");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox64, "eventbox64");
  GLADE_HOOKUP_OBJECT (window_search_prod, checkbutton1_stockA, "checkbutton1_stockA");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox65, "eventbox65");
  GLADE_HOOKUP_OBJECT (window_search_prod, checkbutton2_stockB, "checkbutton2_stockB");
  GLADE_HOOKUP_OBJECT (window_search_prod, eventbox66, "eventbox66");
  GLADE_HOOKUP_OBJECT (window_search_prod, label26, "label26");
  GLADE_HOOKUP_OBJECT (window_search_prod, image16, "image16");

  return window_search_prod;
}

